### PR TITLE
PIE-142: add check_offers endpoint

### PR DESCRIPTION
**Pull request by canadiaLite**
adds check_offers endpoint to docs

### CODE REVIEW

**Comment by canadiaLite** [comment]
response needs offerId as key in response object, not array

**Comment by canadiaLite** [comment]
checkoffers needs to be modified to use standard term object while remaining backwards compatible

**Comment by lesjonesiv** [comment]
Looks like we have some duplication now.

**Comment by canadiaLite** [comment]
> Looks like we have some duplication now.

ah, i didn't realize i could just use the filename to reference an existing type

**Review by lesjonesiv — APPROVED** [review]

**Pull request merged**
